### ISSUE TITLE
krib: install fails, api-server, scheduler and controller manager can't start 

### ISSUE THREAD

**Issue by peterrosell** [digitalrebar/provision-content#225]
Installation of Kubernetes fails when waiting for its base service can't start. Looking in `krib-kubeadm.cfg.tmpl` it provided extra volumes to `controllerManager`, `scheduler` and `apiServer`.
Krib content-package version is `v1.12.0-tip-151-31915dd7430d7119be359e4d684cdab30afda538`.
```
  extraVolumes:
    - name: hyperkube
      hostPath: /k8s/hyperkube
      mountPath: /hyperkube
```
These three containers fail to start. By removing the extra volumes from the kubeadm config all three services start up as expected.

Are these mount of an external hyperkube binary used in the CentOS installation or just something left when testing?
